
---
- name: AWS EC2 Instance Configuration Deploment and Orchestration by MOSUDI ISIAKA (imosudi@gmail.com|http://www.mioemi.com)
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - /vars/ec2_secrets.yml

